name: Build Youtube_Downloader.exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Copy resource files
        run: |
          mkdir dist
          cp Youtube_Downloader/settings.png dist/settings.png
          cp Youtube_Downloader/save_path.txt dist/save_path.txt

      - name: Build exe
        run: pyinstaller --onefile --distpath dist --add-data "dist/settings.png;." --add-data "dist/save_path.txt;." Youtube_Downloader/Youtube_Downloader.py
