name: Package Youtube_Downloader.py with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Package Application
      run: |
        mkdir -p dist
        pyinstaller --onefile --noconsole Youtube_Downloader/Youtube_Downloader.py
        cp Youtube_Downloader/settings.png dist/
        cp Youtube_Downloader/save_path.txt dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: dist/
