
            

name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
            
      with:
        path: Youtube_Downloader/Youtube-Downloader.py

    - uses: actions/upload-artifact@v3
      with:
        name: name-of-artifact
        path: src/dist/windows
